### ISSUE TITLE
Systemd user unit?

### ISSUE THREAD

**Issue by Mikaela** [Limnoria/Limnoria-doc#69]
https://github.com/Limnoria/Limnoria-doc/issues/3

Systemd is also very popular and it has user specific units that according to [Arch wiki](https://wiki.archlinux.org/index.php/Systemd/User#How_it_works) are put into `~/.config/systemd/user/`.

**Comment by ProgVal** [comment]
“This process will survive as long as there is some session for that user, and will be killed as soon as the last session for the user is closed.”
not sure that's what we want.

**Comment by Mikaela** [comment]
[It](https://wiki.archlinux.org/index.php/Systemd/User#Automatic_start-up_of_systemd_user_instances) continues:

> ...Sometimes it may be useful to start it right after boot, and keep the systemd user instance running after the last session closes, for instance to have some user process running without any open session. Lingering is used to that effect. Use the following command to enable lingering for specific user: `# loginctl enable-linger username`

**Comment by Mikaela** [comment]
I didn't get user side systemctl to work, but I think writing systemwide service should be easy and I will take a look at it later.

#3 is also systemwide

**Comment by Mikaela** [comment]
And one kind of service is written (todo: think about writing it to same page as supybot-botchk) and it seems to work.

Put this to `/etc/systemd/system` and run `systemctl daemon-reload`. After you have started the bot at least once with pidfile (like with supybot-botchk), you can `systemctl enable supybot.service && systemctl start supybot.service`.

```service
[Unit]
Description=Supybot
After=network.target

[Service]
Type=forking
PIDFile=/home/bot/botname/botname.pid
ExecStart=/usr/local/bin/supybot /home/bot/botname/botname.conf --daemon
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
User=bot

[Install]
WantedBy=multi-user.target
```

Notes:
* the pid thing was already mentioned
* supybot respawns immediately when it has quit
* commands:
    * autostart on boot: `systemctl enable supybot.service`
    * disable autostart on boot: `systemctl disable supybot.service`
    * start the bot: `systemctl start supybot.service`
    * stop the bot: `systemctl stop supybot.service`
    * reload config files: `systemctl reload supybot.service`
