### ISSUE TITLE
Advanced Plugin Testing example uses invalid getMsg() code

### ISSUE THREAD

**Issue by GLolol** [Limnoria/Limnoria-doc#80]
In http://doc.supybot.aperio.fr/en/latest/develop/advanced_plugin_testing.html#including-extra-setup, the code example shows `m = self.getMsg()`, which is invalid because `getMsg()` requires a `query` argument. Interestingly the command syntax is correct later in the [Utilities](http://doc.supybot.aperio.fr/en/latest/develop/advanced_plugin_testing.html#utilities) section.

**Comment by ProgVal** [comment]
I guess we could update the code to make its argument default to `' '`.
