### ISSUE TITLE
use/install:  Dont recommend using repository versions/managers (Ubuntu, Debian)

### ISSUE THREAD

**Issue by teward** [Limnoria/Limnoria-doc#85]
In Ubuntu and such, most software versions are version locked after the release of the specific version of the OS.

As such, it gets very obsolete quickly in Ubuntu LTS releases.

My suggestion would be PyPI based or from-source installations for Ubuntu.

Could we at least add a warning about how repo versions might be out of date as a warning?

**Comment by ProgVal** [comment]
People on Debian and Ubuntu LTS know (or should know) that their packages are not updated to provide more stability.
Debian has backports for users who want an updated version of Limnoria.

> Could we at least add a warning about how repo versions might be out of date as a warning?

I'll do that
